title: My Jekyll Site
description: A simple Jekyll site with SCSS support.
theme: jekyll-theme-primer

# Set the source folder for Jekyll to the docs folder
source: docs

# Destination folder where the built site will go
destination: docs/_site

# Enable Sass converter for SCSS
sass:
  style: compressed
