title: AdReaper
description: The Ultimate Adblocker Solution
baseurl: ""
url: "https://labibrayan14.github.io/AdReaper"
theme: jekyll-theme-minimal

# Enable SCSS Support
sass:
  style: compressed

# Set the source folder for Jekyll to the docs folder
source: docs

# Destination folder where the built site will go
destination: docs/_site

# Enable Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown Extensions
markdown: kramdown
highlighter: rouge
